# V15 – Netzwerktechnik Grundlagen & Protokolle: Theorie

## 🎯 Lernziele
Nach diesem Notebook kannst du …
- erklären, **warum Rechnernetze in Schichten** modelliert werden und welches Problem das löst,
- die sieben **OSI-Schichten** und die vier Schichten des **TCP/IP-Stacks** benennen, gegeneinander abgrenzen und typische Aufgaben zuordnen,
- **IP-Adressen**, **MAC-Adressen** und **Ports** sicher voneinander unterscheiden und ihre jeweilige Rolle beim Paketversand beschreiben,
- den grundsätzlichen **Aufbau eines Netzwerkpakets** (Header/Payload, Kapselung) erklären,
- den Zweck von **DNS** in einem Satz erklären,
- die industriellen Protokolle **Modbus TCP**, **OPC UA**, **Profinet** und **EtherNet/IP** auf konzeptioneller Ebene einordnen.

## ⏱️ Zeitbudget
Ca. 60 Minuten in Ruhe durcharbeiten.

## 🧭 TL;DR
Netzwerke übertragen Daten nicht in einem Rutsch, sondern in kleinen **Paketen** und durch **mehrere aufeinander aufbauende Schichten**, die je eine Teilaufgabe lösen (Verkabelung, Adressierung, Wegewahl, Anwendungsprotokoll …). In der industriellen Fertigung werden darauf weitere Protokolle aufgesetzt (Modbus TCP, OPC UA, Profinet), die den besonderen Echtzeit- und Robustheitsanforderungen gerecht werden. In diesem Notebook lernst du die konzeptionelle Grundlage – ohne selbst echte Sockets zu programmieren.

## 📦 Voraussetzungen
- [00_python_recap.ipynb](00_python_recap.ipynb)
- Grundverständnis: „Ein Computer hat eine Adresse, Programme tauschen Daten aus
,
,
,

: 
,
: {},
: [
1
,
,
,
,
. Ein **Rechnernetz** ist deshalb immer eine sorgfältig abgestimmte Kombination aus Hardware (Kabel, Switches, Netzwerkkarten) und Software (Protokollen), die zusammen den zuverlässigen Datenaustausch ermöglichen.

> [!NOTE]
> Ein **Protokoll** ist ein verbindliches Regelwerk, das festlegt, **wie** zwei Teilnehmer Daten formatieren, austauschen und bestätigen. Ohne Protokoll wüsste der Empfänger nicht, wo eine Nachricht anfängt, was sie bedeutet und ob sie vollständig angekommen ist.

### 1.1 Das Grundproblem: Komplexität beherrschen

Die Kommunikation zwischen zwei Maschinen enthält eine überraschend große Zahl an Teilproblemen: Wie erkennen die elektrischen Pegel auf dem Kabel eine Null von einer Eins? Wie finden Daten durch ein Netz mit mehreren Wegen ihren Empfänger? Wie wird sichergestellt, dass alle Pakete in der richtigen Reihenfolge und vollständig ankommen? Wie entscheidet die Anwendung, was die empfangenen Bytes eigentlich bedeuten?

Würde man all das in einer einzigen monolithischen Software lösen, wäre der Code unverständlich und unwartbar. Die Informatik nutzt deshalb ein bewährtes Werkzeug: **Abstraktion durch Schichten**. Jede Schicht löst genau eine Teilaufgabe und stellt der darüberliegenden Schicht eine klar definierte Schnittstelle zur Verfügung. Die höhere Schicht muss nicht wissen, wie die tieferen arbeiten – sie verlässt sich nur auf deren Dienste.

## 2. Das OSI-7-Schichten-Modell

Das **OSI-Referenzmodell** (Open Systems Interconnection) der ISO ist der Klassiker unter den Schichtenmodellen. Es ist heute **kein real implementiertes System**, aber das gemeinsame Vokabular, mit dem Netzwerktechniker und -technikerinnen über Probleme sprechen. Wer „Layer 2 ist tot
,
,
,
,
,
,
2
,
3
,
4
,
5
,
6
,
7

: 
,
: null,
: {},
: [],
: [
,
diagramme/01_osi_modell.mmd", encoding="utf-8") as f:
    display(Markdown(f"```mermaid\n{f.read()}\n```"))

### 2.1 Merkhilfe und pragmatische Einordnung

Ein verbreiteter Merksatz für die sieben Schichten von unten nach oben lautet „**P**lease **D**o **N**ot **T**hrow **S**ausage **P**izza **A**way
5
,
,
,

### 2.2 Was OSI nicht leistet

Das OSI-Modell ist bewusst **abstrakt** gehalten und sagt nichts darüber, wie die einzelnen Schichten konkret zu implementieren sind. Es ist ein **Denkwerkzeug**, kein Bauplan. In der Praxis gibt es daher auch Unschärfen: TLS etwa wird je nach Lehrbuch mal Schicht 6, mal Schicht 5 zugeordnet, und viele Anwendungsprotokolle überspringen die Schichten 5 und 6 schlicht. Lass dich von solchen Einordnungsdebatten nicht verunsichern – das Modell hilft beim Strukturieren, nicht beim Haarspalten.

## 3. Der TCP/IP-Stack – das Modell der realen Welt

Das **TCP/IP-Referenzmodell** ist das Schichtenmodell, mit dem das heutige Internet tatsächlich gebaut ist. Es ist **pragmatischer** als OSI und fasst die sieben Schichten in vier zusammen:

1. **Netzzugangsschicht (Link Layer)** – entspricht OSI 1+2. Kümmert sich um das konkrete Übertragungsmedium: Ethernet, WLAN, Glasfaser, Mobilfunk.
2. **Internet-Schicht (Internet Layer)** – entspricht OSI 3. Beherbergt das **Internet Protocol (IP)** in den Varianten IPv4 und IPv6. Hier werden Pakete über Grenzen einzelner Netze hinweg zugestellt.
3. **Transportschicht (Transport Layer)** – entspricht OSI 4. Die beiden wichtigen Vertreter sind **TCP** (verbindungsorientiert, zuverlässig, geordnet) und **UDP** (verbindungslos, schnell, ohne Garantie).
4. **Anwendungsschicht (Application Layer)** – entspricht OSI 5–7 zusammengefasst. Hier leben alle konkreten Protokolle: HTTP, HTTPS, DNS, SMTP, Modbus TCP, OPC UA.

> [!NOTE]
> Das **TCP/IP-Modell** ist nicht nur ein Modell, sondern auch eine Familie tatsächlich spezifizierter Protokolle. Es ist damit konkreter und näher an der Implementierung als OSI.

In [1]:
from IPython.display import Markdown, display
with open("diagramme/02_tcp_ip_stack.mmd", encoding="utf-8") as f:
    display(Markdown(f"```mermaid\n{f.read()}\n```"))

```mermaid
flowchart TB
    A["Anwendungsschicht<br/>HTTP, DNS, MQTT, OPC UA"]
    T["Transportschicht<br/>TCP (zuverlaessig), UDP (schnell)"]
    I["Internetschicht<br/>IP, ICMP, Routing"]
    N["Netzzugangsschicht<br/>Ethernet, WLAN, PROFINET"]
    A --> T --> I --> N

```

### 3.1 TCP vs. UDP – zwei sehr verschiedene Dienste

Auf der Transportschicht stehen zwei grundlegend unterschiedliche Werkzeuge zur Verfügung. **TCP (Transmission Control Protocol)** baut vor dem Senden eine logische Verbindung auf (Handshake), sorgt für die Reihenfolge der Pakete, fordert verlorene Pakete erneut an und regelt die Senderate abhängig von der Netzauslastung. TCP ist damit **zuverlässig, aber mit Overhead** verbunden und eignet sich für Dateien, Web-Zugriffe, Datenbankverbindungen und industrielle Steuerungsprotokolle wie Modbus TCP oder OPC UA.

**UDP (User Datagram Protocol)** verschickt einzelne Datagramme ohne Verbindungsaufbau und ohne jede Garantie: Pakete können verloren gehen, doppelt ankommen oder in falscher Reihenfolge eintreffen. Dafür ist UDP **extrem schnell und ressourcenschonend** – ideal für Live-Video, Audio, Gaming, DNS-Anfragen oder sensornahe IoT-Protokolle wie MQTT-SN, bei denen ein einzelnes verlorenes Paket weniger wichtig ist als geringe Latenz.

> [!WARNING]
> „UDP ist unzuverlässig

: 
,
: {},
: [
3.2

: 
,
: {},
: [
4

255
4
3
,
128
,
,
8
12
16

: 
,
: {},
: [
4.1
,
,
24
,
,
,
24
24
256

: 
,
: null,
: {},
: [],
: [
,
192.168.10.100"
oktette = [int(x) for x in ip.split(".")]
print(f"Oktette: {oktette}")
print(f"Gehört zum Netz 192.168.10.0/24: {oktette[:3] == [192, 168, 10]}")

## 5. MAC-Adressen: die unveränderliche Geräte-Kennung

Eine **MAC-Adresse (Media Access Control)** identifiziert eine Netzwerkkarte auf der Sicherungsschicht. Sie ist 48 Bit lang und wird üblicherweise als sechs hexadezimale Paare geschrieben, etwa `00:1A:2B:3C:4D:01`. Die ersten drei Byte sind die **OUI (Organizationally Unique Identifier)** und identifizieren den Hersteller, die letzten drei Byte sind eine herstellerinterne Gerätenummer.

Im Gegensatz zur IP-Adresse, die sich ändert, sobald ein Gerät in ein anderes Netz wandert, ist die MAC-Adresse in der Regel **werkseitig fest** und bleibt gleich, solange die Netzwerkkarte existiert. Deshalb nutzt man MAC-Adressen in industriellen Netzen häufig als eindeutige Kennung für Geräte, z. B. um einem bestimmten Roboter per DHCP-Reservierung immer dieselbe IP-Adresse zuzuteilen.

> [!WARNING]
> MAC-Adressen lassen sich softwareseitig ändern („MAC-Spoofing

: 
,
: {},
: [
5.1

## 6. Ports: mehrere Programme auf einem Rechner

Ein Rechner hat eine IP-Adresse, aber meist laufen darauf **viele Programme parallel**, die alle ins Netz kommunizieren wollen: ein Webserver, ein Datenbankserver, ein OPC-UA-Server. Damit die Transportschicht weiß, an welches dieser Programme ein eingehendes Paket gerichtet ist, nutzt sie **Ports** – 16-Bit-Zahlen von 0 bis 65535, die innerhalb eines Rechners wie interne Hausnummern wirken.

> [!NOTE]
> Ein **Port** ist eine Zahl, die zusammen mit der IP-Adresse einen konkreten **Endpunkt** (Socket) auf einem Rechner bezeichnet. Ohne Port wüsste der Empfangs-Stack nicht, welches der laufenden Programme die Daten bekommen soll.

Die **IANA** teilt den Portbereich in drei Zonen ein:

- **Well-Known Ports (0–1023)** – fest zugeordnete Ports für Standarddienste, benötigen auf Unix-Systemen Root-Rechte zum Öffnen.
- **Registered Ports (1024–49151)** – halbwegs gebräuchliche Ports für bekannte Anwendungen, formal bei der IANA registriert.
- **Dynamic / Private Ports (49152–65535)** – freie Ports für kurzlebige Verbindungen, werden vom Betriebssystem automatisch vergeben.

### 6.1 Wichtige Ports für dich

| Port | Protokoll | Dienst |
|---|---|---|
| 22 | TCP | SSH (Fernzugriff) |
| 53 | UDP/TCP | DNS |
| 80 | TCP | HTTP (Web, unverschlüsselt) |
| 443 | TCP | HTTPS (Web, TLS-verschlüsselt) |
| 502 | TCP | **Modbus TCP** (Industrie-SPS) |
| 1883 | TCP | MQTT (IoT, unverschlüsselt) |
| 4840 | TCP | **OPC UA** (Standardport) |
| 44818 | TCP | EtherNet/IP (Rockwell) |

In [2]:
# Offline-Demo: zu einem Port den Dienst nachschlagen
port_dienste = {80: "HTTP", 443: "HTTPS", 502: "Modbus TCP", 4840: "OPC UA"}
for port, name in port_dienste.items():
    print(f"Port {port:5d} → {name}")

Port    80 → HTTP
Port   443 → HTTPS
Port   502 → Modbus TCP
Port  4840 → OPC UA


## 7. Aufbau eines Netzwerkpakets: Header und Payload

Jedes Paket, das über ein Netz läuft, folgt demselben Grundschema: Zuerst kommen ein oder mehrere **Header**, dann die **Nutzdaten (Payload)**. Die Header enthalten Steuerinformationen (Absender, Empfänger, Reihenfolge, Prüfsumme), die Payload enthält die eigentliche Nachricht der Anwendung.

Durch die Kapselung entsteht eine geschachtelte Struktur: Eine HTTP-Anfrage wird in einen TCP-Segment-Header eingebettet, das wiederum in einen IP-Paket-Header eingebettet, das wiederum in einen Ethernet-Rahmen eingebettet wird. Jeder Header addiert einige Byte Overhead, weshalb die **Nutzdatenrate** immer etwas niedriger ist als die **Bruttorate** des Mediums.

> [!TIP]
> Eine typische Ethernet-MTU (maximale Paketgröße) liegt bei 1500 Byte. Davon gehen etwa 20 Byte für den IP-Header und 20 Byte für den TCP-Header ab, sodass für deine Anwendungsdaten pro Paket rund 1460 Byte bleiben.

In [3]:
from IPython.display import Markdown, display
with open("diagramme/03_paket_struktur.mmd", encoding="utf-8") as f:
    display(Markdown(f"```mermaid\n{f.read()}\n```"))

```mermaid
flowchart LR
    ETH["Ethernet-Header<br/>MAC-Adressen"]
    IP["IP-Header<br/>Quell-/Ziel-IP"]
    TCP["TCP-/UDP-Header<br/>Ports"]
    DATA["Nutzdaten<br/>z.B. Modbus-Befehl"]
    CRC["CRC<br/>Pruefsumme"]
    ETH --> IP --> TCP --> DATA --> CRC

```

### 7.1 Was steht in einem IP-Header?

Der IPv4-Header enthält unter anderem die **Quell-IP**, die **Ziel-IP**, die **Paketlänge**, ein **Time-to-Live-Feld (TTL)**, das bei jedem Router dekrementiert wird und verhindert, dass Pakete ewig kreisen, sowie eine **Header-Prüfsumme**. Diese Felder zusammen sind rund 20 Byte groß und ermöglichen es jedem Zwischenknoten (Router), das Paket auszuwerten und weiterzuleiten, ohne die Nutzdaten interpretieren zu müssen.

### 7.2 Was steht in einem TCP-Header?

Der TCP-Header enthält neben **Quell- und Ziel-Port** auch die **Sequenznummer**, die **Bestätigungsnummer**, **Flags** für den Verbindungsaufbau (SYN, ACK, FIN) und ein **Fenstergröße**-Feld zur Flusskontrolle. Die Sequenznummer ist der Mechanismus, mit dem TCP Pakete in der richtigen Reihenfolge wieder zusammensetzt, auch wenn sie auf dem Weg durcheinander geraten sind.

## 8. DNS – das Telefonbuch des Internets

Menschen merken sich `beispiel.de` leichter als `93.184.216.34`. Das **Domain Name System (DNS)** übersetzt einen menschenlesbaren Namen in eine IP-Adresse. Die Abfrage läuft hierarchisch: Dein Rechner fragt einen lokalen Resolver, der fragt wiederum die zuständigen Nameserver, bis am Ende eine IP zurückkommt – alles üblicherweise innerhalb weniger Millisekunden.

In Industrienetzen spielt DNS eine untergeordnete Rolle, weil Maschinenadressen meist fest konfiguriert sind. Für die Anbindung an übergeordnete IT-Systeme (ERP, MES, Cloud) ist DNS aber genauso relevant wie im klassischen Büro-Netz.

> [!NOTE]
> **DNS** ist selbst ein Anwendungsprotokoll, das meist über UDP auf Port 53 läuft und Namensauflösungen bearbeitet.

## 9. Industrienetze: Besonderheiten in der Fertigung

Ein Büro-Netz transportiert E-Mails und Webseiten – wenn ein Paket 200 ms später ankommt, merkt es niemand. In einer Produktionsanlage darf ein Not-Aus-Signal **nicht** 200 ms brauchen. Industrielle Netze stellen deshalb ergänzende Anforderungen:

- **Echtzeitfähigkeit** – garantierte, deterministische Latenz (bei Profinet IRT bis in den Mikrosekunden-Bereich),
- **Robustheit** – tolerant gegenüber elektromagnetischer Störung, Staub, Vibration und Temperatur,
- **Diagnosefähigkeit** – jeder Teilnehmer meldet seinen Gesundheitszustand zur frühzeitigen Fehlererkennung,
- **Interoperabilität** – Geräte verschiedener Hersteller müssen dieselbe Sprache sprechen.

Die dafür entwickelten Protokolle werden meistens **auf** das klassische TCP/IP **aufgesetzt**, so dass dieselbe Ethernet-Infrastruktur genutzt werden kann:

- **Modbus TCP** – simples Client/Server-Protokoll auf Port 502, 1979 ursprünglich für RS-485 entwickelt, heute in einer TCP-Variante allgegenwärtig in kleinen SPS. Vorteil: Extrem einfach, viele Bibliotheken. Nachteil: Keine Typinformation, keine Verschlüsselung, veraltetes Datenmodell.
- **OPC UA** (Open Platform Communications – Unified Architecture) – moderner Industrie-4.0-Standard, Port 4840. Beschreibt Maschinen als hierarchischen **Informationsraum** aus Knoten und Variablen, bringt Typsystem, Verschlüsselung, Authentifizierung und plattformunabhängige Clients mit.
- **Profinet** – Siemens-geprägter Echtzeit-Standard auf Basis von Ethernet. In der Variante **Profinet IRT** mit Hardware-Zeitsynchronisation für harte Echtzeitanforderungen in Motion Control.
- **EtherNet/IP** – Rockwell-geprägter US-Standard, nutzt das **Common Industrial Protocol (CIP)** über TCP/UDP auf Port 44818.
- **MQTT** – Publish-Subscribe-Protokoll auf Port 1883, beliebt in der Sensorik/IoT wegen extrem geringer Datenmengen.

> [!WARNING]
> Nur weil ein Protokoll **Ethernet als Medium** nutzt, ist es noch kein Büro-Ethernet. Profinet IRT beispielsweise taktet Switches hardwareseitig und verträgt sich nicht beliebig mit allgemeiner IT-Hardware.

In [4]:
from IPython.display import Markdown, display
with open("diagramme/04_industrienetz.mmd", encoding="utf-8") as f:
    display(Markdown(f"```mermaid\n{f.read()}\n```"))

```mermaid
flowchart TB
    SCADA["SCADA-Server<br/>192.168.10.200"]
    SW["Industrial Switch"]
    CNC1["CNC-01<br/>Modbus TCP<br/>192.168.10.100"]
    CNC2["CNC-02<br/>Modbus TCP<br/>192.168.10.101"]
    ROB["Robot-01<br/>MQTT / OPC UA<br/>192.168.10.102"]
    PRESS["Press-01<br/>Modbus TCP<br/>192.168.10.103"]
    SENS["Sensor-01<br/>MQTT<br/>192.168.10.104"]
    SCADA --- SW
    SW --- CNC1
    SW --- CNC2
    SW --- ROB
    SW --- PRESS
    SW --- SENS

```

### 9.1 Warum OPC UA die Zukunft ist

OPC UA ist das einzige der industriellen Protokolle, das von Grund auf für die Anforderungen der vernetzten Fabrik entworfen wurde. Es bringt von Haus aus ein objektorientiertes **Informationsmodell** mit, in dem Maschinen ihre Variablen selbst beschreiben („Drehzahl in U/min, Datentyp Double, nur lesbar
,
,
,
,
,

: 
,
: {},
: [
10
,
,
2. **Transportschicht** – TCP bekommt dieses Byte-Paket und setzt einen Header davor, in dem Ziel-Port 4840 und Quell-Port (z. B. 52341) stehen, dazu Sequenznummern zur Reihenfolgesicherung.
3. **Internet-Schicht** – IP ergänzt einen weiteren Header mit Quell-IP `192.168.10.100` und Ziel-IP `192.168.10.200`.
4. **Netzzugangsschicht** – Ethernet fügt schließlich einen Rahmen mit Quell-MAC und Ziel-MAC hinzu und verschickt das Ganze als elektrisches Signal über das Kabel.

Am Empfänger laufen dieselben Schritte rückwärts: Ethernet packt aus und reicht nach oben, IP packt aus und reicht nach oben, TCP rekonstruiert die ursprüngliche Reihenfolge, und der OPC-UA-Server auf Port 4840 interpretiert schließlich die Nachricht.

## 11. Weiterführend

> [!TIP]
> Wer sich tiefer einlesen möchte, dem seien die Standards **IEEE 802.3 (Ethernet)**, **RFC 791 (IP)**, **RFC 793 (TCP)** und **IEC 62541 (OPC UA)** empfohlen. Diese sind die Primärquellen – alles andere (Wikipedia, Lehrbücher) ist Sekundärliteratur.

## 12. Selbst-Checks

Beantworte dir die folgenden Fragen im Kopf und klappe erst dann die Musterantwort auf.

<details><summary>1. Wieso teilt man Netzwerke überhaupt in Schichten?</summary>

Um die überwältigende Komplexität der Datenkommunikation in handhabbare Teilprobleme zu zerlegen. Jede Schicht löst eine klar abgegrenzte Aufgabe und bietet der darüberliegenden Schicht einen wohldefinierten Dienst an, ohne dass die höhere Schicht Details der tieferen kennen muss.
</details>

<details><summary>2. Welche vier Schichten hat der TCP/IP-Stack?</summary>

Netzzugang, Internet, Transport, Anwendung.
</details>

<details><summary>3. Welcher Unterschied besteht zwischen einer IP-Adresse und einer MAC-Adresse?</summary>

Die IP-Adresse ist logisch und wechselt beim Umziehen in ein anderes Netz; die MAC-Adresse ist hardwareseitig (meist) fest und identifiziert die Netzwerkkarte selbst. IP wirkt auf der Vermittlungsschicht über Netze hinweg, MAC nur auf der Sicherungsschicht im lokalen Segment.
</details>

<details><summary>4. Welches Protokoll spricht die Maschine, wenn sie Port 502 nutzt?</summary>

Modbus TCP – das klassische Industrieprotokoll zur Abfrage von SPS-Registern.
</details>

<details><summary>5. Wann ist UDP die bessere Wahl als TCP?</summary>

Immer dann, wenn niedrige Latenz wichtiger ist als die garantierte Zustellung einzelner Pakete: Echtzeit-Audio, Video, manche Sensor- und Telemetrie-Protokolle. Verlorene Pakete werden dort gar nicht erst erneut angefordert.
</details>

<details><summary>6. Warum hat jedes Paket einen Header und Payload?</summary>

Der Header enthält die Steuerinformation (wer, wohin, wie lang, in welcher Reihenfolge, welche Prüfsumme), die Payload die eigentlichen Anwendungsdaten. Ohne Header wüsste weder ein Zwischenknoten noch der Empfänger, was mit dem Paket zu tun ist.
</details>

<details><summary>7. Was übernimmt DNS konkret?</summary>

Die Übersetzung menschenlesbarer Namen (z. B. `beispiel.de`) in maschinenlesbare IP-Adressen. Ohne DNS müsstest du dir für jeden Dienst die IP merken.
</details>

<details><summary>8. Warum kann man OPC UA guten Gewissens als Industrie-4.0-Standard bezeichnen?</summary>

Weil OPC UA Plattformunabhängigkeit, ein objektorientiertes Informationsmodell, Authentifizierung, Verschlüsselung und Skalierbarkeit von der Sensorik bis zur Cloud mitbringt – Eigenschaften, die ältere Protokolle wie Modbus TCP nicht von Haus aus haben.
</details>

## ✅ Zusammenfassung
- OSI und TCP/IP sind zwei Schichtenmodelle mit demselben Grundgedanken: Komplexität in klar umrissene Teilprobleme aufteilen.
- IP-Adresse, MAC-Adresse und Port beantworten drei verschiedene Fragen: welches logische Netz, welches Gerät auf dem Kabel, welches Programm auf dem Gerät.
- Pakete bestehen immer aus Header(n) und Payload und werden beim Versenden Schicht für Schicht eingepackt.
- Industrienetze setzen spezielle Protokolle (Modbus TCP, OPC UA, Profinet, EtherNet/IP) auf klassisches TCP/IP auf, um Echtzeit-, Robustheits- und Diagnoseanforderungen zu erfüllen.

## ➡️ Nächster Schritt
Weiter mit [02_praxis.ipynb](02_praxis.ipynb).